version: "3.7"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks: 
      - webnet
  app:
    image: dongjae93/sdc
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role != manager]	
    ports:
      - "80:3000"
    depends_on:
      - mongo
    networks: 
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks: 
    webnet: